name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 20 * * *' # run at UTC 8 pm

env:
  ZIG_VERSION: 0.16.0

jobs:
  test-all-targets:
    strategy:
      matrix:
        include:
          - optimization: 'Debug'
          - optimization: 'ReleaseSafe'

    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan-dev vulkan-tools

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Check formatting
        run:  |
          zig fmt --check .

      - name: Build application
        run: |
          zig build -Doptimize=${{ matrix.optimization }} --summary all

      - name: Run unit tests
        run: |
          zig build -Doptimize=${{ matrix.optimization }} test --summary all
